### PR TITLE
Depthai USB and process watchdog

### PR DESCRIPTION
**Pull request by szabi-luxonis**
This PR contains:
-USB watchdog, restart depthai on USB disconnection
-Process watchdog, on any non-recoverable SW error restart the depthai process (depthai_supervisor.py)
-test.py was renamed to depthai.py, for backward compatibility a symlink is set test.py -> depthai_supervisor.py

### CODE REVIEW

**Comment by Luxonis-Brian** [comment]
Everything seems to be working, but I think I was able to find a hole. If I press RST button once, the device always seems to recover. But if I press the RST button a second time as soon as the MX is booting back up, I can get it error. It looks like this happens if I reset during device firmware load. 



> Failed to open stream meta_d2h ! Retrying ...
> E: [global] [    854568] [python3] XLinkOpenStream:1227	/home/gszabi/WORK/luxonis/depthai/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1227
> 	 Assertion Failed: link != NULL
> Failed to open stream meta_d2h ! Retrying ...
> Stream not opened: meta_d2h
> depthai: meta_d2h error;
> depthai: INIT OK! 
> watchdog triggered 
> Stopping threads: ...
> Stopping threads: DONE.
> Closing all observer streams: ...
> Closing all observer streams: DONE.
> XLink initialized.
> No USB device [03e7:2485], still looking... 0.305s [FOUND]
> Sending device firmware "cmd_file": /home/luxonis-test/Desktop/depthai-python-extras/depthai.cmd 
> process watchdog timeout
> Return code:10
> No calibration file. Using Calibration Defaults.
> Using Arguments= {'config_overwrite': None, 'device_id': '', 'dev_debug': None}
> depthai.__version__ == 0.0.10a
> depthai.__dev_version__ == 1031fdb60770e43db38958d239f482d4c77676f5
> XLink initialized.
> Sending device firmware "cmd_file": /home/luxonis-test/Desktop/depthai-python-extras/depthai.cmd **_<----------------PRESSED RST BUTTON HERE_**
> Failed to find booted device after boot, err code 5
> depthai: Error initializing xlink
> Error initializing device. Try to reset it.
> terminate called after throwing an instance of 'std::system_error'
>   what():  Invalid argument
> Aborted (core dumped)
> Return code:134
> Failed to open stream meta_d2h ! Retrying ...
> E: [global] [    854568] [python3] XLinkOpenStream:1227	/home/gszabi/WORK/luxonis/depthai/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1227
> 	 Assertion Failed: link != NULL
> Failed to open stream meta_d2h ! Retrying ...
> Stream not opened: meta_d2h
> depthai: meta_d2h error;
> depthai: INIT OK!
> watchdog triggered 
> Stopping threads: ...
> Stopping threads: DONE.
> Closing all observer streams: ...
> Closing all observer streams: DONE.
> XLink initialized.
> No USB device [03e7:2485], still looking... 0.305s [FOUND]
> Sending device firmware "cmd_file": /home/luxonis-test/Desktop/depthai-python-extras/depthai.cmd
> process watchdog timeout
> Return code:10
> No calibration file. Using Calibration Defaults.
> Using Arguments= {'config_overwrite': None, 'device_id': '', 'dev_debug': None}
> depthai.__version__ == 0.0.10a
> depthai.__dev_version__ == 1031fdb60770e43db38958d239f482d4c77676f5
> XLink initialized.
> Sending device firmware "cmd_file": /home/luxonis-test/Desktop/depthai-python-extras/depthai.cmd
> Failed to find booted device after boot, err code 5
> depthai: Error initializing xlink
> Error initializing device. Try to reset it.
> terminate called after throwing an instance of 'std::system_error'
>   what():  Invalid argument
> Aborted (core dumped)
> Return code:134

.
.
.
this same looping error repeated for a minute or two, and then I noticed a new error was looping until I finally cut power to the DUT (at bottom):
.
.
.

> Return code:134
> No calibration file. Using Calibration Defaults.
> Using Arguments= {'config_overwrite': None, 'device_id': '', 'dev_debug': None}
> depthai.__version__ == 0.0.10a
> depthai.__dev_version__ == 1031fdb60770e43db38958d239f482d4c77676f5
> XLink initialized.
> Sending device firmware "cmd_file": /home/luxonis-test/Desktop/depthai-python-extras/depthai.cmd
> Failed to boot the device: 5-ma2480, err code 3
> depthai: Error initializing xlink
> Error initializing device. Try to reset it.
> terminate called after throwing an instance of 'std::system_error'
>   what():  Invalid argument
> Aborted (core dumped)
> Return code:134
> No calibration file. Using Calibration Defaults.
> Using Arguments= {'config_overwrite': None, 'device_id': '', 'dev_debug': None}
> depthai.__version__ == 0.0.10a
> depthai.__dev_version__ == 1031fdb60770e43db38958d239f482d4c77676f5
> XLink initialized.
> Sending device firmware "cmd_file": /home/luxonis-test/Desktop/depthai-python-extras/depthai.cmd
> Failed to boot the device: 5-ma2480, err code 3
> depthai: Error initializing xlink
> Error initializing device. Try to reset it.
> terminate called after throwing an instance of 'std::system_error'
>   what():  Invalid argument
> Aborted (core dumped)
> Return code:134
> No calibration file. Using Calibration Defaults.
> Using Arguments= {'config_overwrite': None, 'device_id': '', 'dev_debug': None}
> depthai.__version__ == 0.0.10a
> depthai.__dev_version__ == 1031fdb60770e43db38958d239f482d4c77676f5
> XLink initialized.
> No USB device [03e7:2485], still looking... 4.957s Traceback (most recent call last):
> No USB device [03e7:2485], still looking... 4.957s   File "test.py", line 38, in <module>
> No USB device [03e7:2485], still looking... 4.957s     p.wait()
> No USB device [03e7:2485], still looking... 4.957s   File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
> No USB device [03e7:2485], still looking... 4.958s     (pid, sts) = self._try_wait(0)
> No USB device [03e7:2485], still looking... 4.958s   File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
> No USB device [03e7:2485], still looking... 4.958s     (pid, sts) = os.waitpid(self.pid, wait_flags)
> No USB device [03e7:2485], still looking... 4.958s KeyboardInterrupt
> No USB device [03e7:2485], still looking... 4.958s Stopping subprocess with pid:  554
> No USB device [03e7:2485], still looking... 4.958s Stopped!
> luxonis-test@luxonis-test:~/Desktop/depthai-python-extras$ ^C
> luxonis-test@luxonis-test:~/Desktop/depthai-python-extras$ ^C
> luxonis-test@luxonis-test:~/Desktop/depthai-python-extras$

**Comment by Luxonis-Brian** [comment]
I switched over to testing on the RPI4 (USB3 port) and tried some of the same things. Again, everything worked well, but I was able to cause trouble when I pushed the RST button a second time during firmware load. 

Edit - after a bit more testing, it just looks like any RST during any firmware load causes trouble, which makes sense. 

Just looks like we don't have this case explicitly covered.

> E: [global] [    261221] [python3] XLinkCloseStream:1316	/work/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1316
> 	 Assertion Failed: link != NULL
> Closing stream metaout: DONE.
> Thread for metaout finished.
> Closing stream meta_d2h: ...
> E: [global] [    261221] [python3] XLinkCloseStream:1316	/work/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1316
> 	 Assertion Failed: link != NULL
> Closing stream meta_d2h: DONE.
> Thread for meta_d2h finished.
> Stopping threads: DONE.
> Closing all observer streams: ...
> Closing all observer streams: DONE.
> XLink initialized.
> Sending device firmware "cmd_file": /home/pi/Desktop/1098OBC_TEST/depthai-python-extras/depthai.cmd **<----- PRESSING RST HERE**
> Failed to boot the device: 1.3-ma2480, err code 3
> depthai: Error initializing xlink
> Segmentation fault
> pi@raspberrypi:~/Desktop/1098OBC_TEST/depthai-python-extras $ 

Sometimes pressing the RST button during device firmware load will result in this:

> Closing stream meta_d2h: DONE.
> Thread for meta_d2h finished.
> Closing stream previewout: ...
> E: [global] [    698564] [python3] XLinkCloseStream:1316	/work/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1316
> 	 Assertion Failed: link != NULL
> Closing stream previewout: DONE.
> Thread for previewout finished.
> Stopping threads: DONE.
> Closing all observer streams: ...
> Closing all observer streams: DONE.
> XLink initialized.
> Sending device firmware "cmd_file": /home/pi/Desktop/1098OBC_TEST/depthai-python-extras/depthai.cmd **<----- PRESSING RST HERE**
> process watchdog timeout
> pi@raspberrypi:~/Desktop/1098OBC_TEST/depthai-python-extras $

**Comment by Luxonis-Brandon** [comment]
Thanks @Luxonis-Brian .  So @szabi-luxonis I think this is good to go.  I think we can just know that this reset-condition possibilitiy exists, but since it seems so improbable, leave it for now.

Thoughts?  

Thanks again, Brian and Szabi

**Comment by Luxonis-Brian** [comment]
Agree @Luxonis-Brandon, this is a huge improvement over what we had. Thanks @szabi-luxonis! 

I'm very excited to use this for testing as well. I will be able to swap out boards before the watchdog timer runs out, so I can leave the script running and testing speed will greatly increase!

**Comment by szabi-luxonis** [comment]
@Luxonis-Brian  when this error happens, do you see an error message printed by kernel?
run `dmesg -w` in terminal
[161999.126288] debugfs: Directory '14' with parent 'devices' already present!
Note, instead of 14 you might see any other number.
If you unplug USB from host, can it recover?

**Comment by szabi-luxonis** [comment]
@Luxonis-Brian or these ? :
`]162524.315127] xhci_hcd 0000:00:14.0: WARN Event TRB for slot 33 ep 1 with no TDs queued?
[162524.315128] xhci_hcd 0000:00:14.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.`

**Comment by Luxonis-Brian** [comment]
Checking now - will edit this comment. .

**Comment by Luxonis-Brandon** [comment]
OK so one thing I noticed on this is that when hitting `q` on the OpenCV preview, the watchdog actually treats this as a crash and restarts the app.

What is the proper way to kill the program?

Otherwise this is LGTM.

**Pull request merged**
