### PR TITLE
Load depthai-api repo as a submodule

### PR DESCRIPTION
**Pull request by itsderek23**
This loads the `depthai-api` Git repo as a submodule.

The `depthai-api` repo contains the host-side code that is used to build the Python `.so` file. End users do not need to grab this submodule unless they are building the `so` file from source.

Instructions for building the `so` file will be within the `depthai-api` repo README.

Run the following to grab the submodule:

```
git submodule update --init
```

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Super exciting that this is progressing!  Will be great for users to be able to build the host side on their own custom platforms/OS/dependencies/etc.

**Comment by alex-luxonis** [comment]
Referenced the [depthai-api](https://github.com/luxonis/depthai-api) submodule in README.md and added basic instructions to init and build.
Not using `--recursive` for submodule init, as that would fetch some large (and unused by us) modules in opencv/dldt.

**Comment by itsderek23** [comment]
I tested w/a fresh checkout on the RPi Compute. It builds w/o any options for the `make` jobs.

Two issues I see after building and running `git status`:

```
modified:   depthai-api (untracked content)
modified:   depthai.cpython-37m-arm-linux-gnueabihf.so
```

## modified:   depthai-api (untracked content)

To get rid of this, I wonder if we need to do the following [via Stackoverflow](https://stackoverflow.com/a/52722775):

```
git rm -rf --cached depthai-api
git add depthai-api
```

## modified:   depthai.cpython-37m-arm-linux-gnueabihf.so

I wonder if the binary file is different because of merging #43? I'm concerned about losing the `.so` files updates in #43 after merging. Is the safest thing running `./depthai-api/build_py_module.sh` after merging to generate a new `so`, then committing that?

**Comment by alex-luxonis** [comment]
```
modified:   depthai.cpython-36m-x86_64-linux-gnu.so
```
We didn't update the x86_64 lib for the latest `depthai-api` changes related to USB3. Maybe we should do this for consistency? (for now only the RPi lib is updated).
But anyway, the file may appear `modified` after a rebuild, even if built with the same source code, as some absolute paths from the build machine get embedded into the binary.


As for the untracked content in `depthai-api`, could you check:
```
depthai-api$ git status
```
I don't get this on my machine (the `build` dir should be already in .gitignore

**Pull request merged**
