### PR TITLE
Save calibration & board config to EEPROM

### PR DESCRIPTION
**Pull request by alex-luxonis**
New options added to `depthai.py`:
```
  -fv FIELD_OF_VIEW, --field-of-view FIELD_OF_VIEW
                        Field of view for the stereo cameras in [deg]
  -b BASELINE, --baseline BASELINE
                        Left/Right camera baseline in [cm]
  -r RGB_BASELINE, --rgb-baseline RGB_BASELINE
                        Distance the RGB camera is from the Left camera
  -w, --no-swap-lr      Do not swap the Left and Right cameras
  -e, --store-eeprom    Store the calibration and board_config (fov,
                        baselines, swap-lr) in the EEPROM onboard
  --clear-eeprom        Invalidate the calib and board_config from EEPROM
  -o, --override-calib  Use the calib and board_config from host, ignoring the
                        EEPROM data if programmed
```

New options added to `calibrate.py`:
```
  -fv FIELD_OF_VIEW, --field-of-view FIELD_OF_VIEW
                        Field of view for the stereo cameras in [deg]
  -b BASELINE, --baseline BASELINE
                        Left/Right camera baseline in [cm]
  -w, --no-swap-lr      Do not swap the Left and Right cameras
```

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks @alex-luxonis !  So quick question on field of view... is that diagonal or horizontal?

**Comment by Luxonis-Brandon** [comment]
So other than specifying which FOV this means, this LGTM.  And @Luxonis-Brian checked it out and it LGTH as well.  So I'd say feel free to go with this @alex-luxonis !

**Comment by Luxonis-Brian** [comment]
The horizontal FOV should actually be 71.86, and the vertical should be 56.74.

**Comment by alex-luxonis** [comment]
Note `depthai_usb2.cmd` was not rebuilt here!

**Comment by Luxonis-Brandon** [comment]
Should we do that for now @alex-luxonis or should we do one of the approaches for supporting USB2-only that you or Szabi mentioned the other day?

**Pull request merged**
