### PR TITLE
add script to run depth stream after succesful calibration

### PR DESCRIPTION
**Pull request by szabi-luxonis**
Usage: python3 calibrate_and_test.py
Functionality: On succesful calibration, depth stream is automatically opened for quality verification.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
LGTM.  Sorry about delay.

**Comment by Luxonis-Brandon** [comment]
Thoughts @Luxonis-Brian ?

**Comment by ElectronBastion** [comment]
Oh thanks for the ping @Luxonis-Brandon. 

Yes, @szabi-luxonis, I've used your work here successfully several times now. I believe it is OK to be released. 

Thank you.

**Comment by Luxonis-Brian** [comment]
Sorry, Chrome signed me in under the wrong account. 

Oh thanks for the ping @Luxonis-Brandon.

Yes, @szabi-luxonis, I've used your work here successfully several times now. I believe it is OK to be released.

Thank you.

**Pull request merged**
