### PR TITLE
Check if udev rules are set

### PR DESCRIPTION
**Pull request by szabi-luxonis**
Check if udev rules are set and fix quit on 'q' keypress.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
So checking if the USB rules are set works great!  The flashing message is nice too.  

image


One improvement is probably worthwhile though: stop attempting to connect (and thereby stop showing the message) after it's determined once that the USB rules are not set.

See the video below:
[https://photos.app.goo.gl/Cfb6pYKu4vmzVxT38](https://photos.app.goo.gl/Cfb6pYKu4vmzVxT38)

Background:
So the first messages stopped where you could read it, but then after say a second the screen started spamming more messages, making it hard to read.

Stopping after the first message would make this awesome.  I would assume not hard as well?

Thoughts?

Thanks,
Brandon

**Comment by szabi-luxonis** [comment]
fixed, @Luxonis-Brandon

**Comment by Luxonis-Brandon** [comment]
Thanks, just tested and this LGTM.  I think it's good to merge @szabi-luxonis !

image

**Comment by Luxonis-Brandon** [comment]
Oh one more thing @szabi-luxonis .  So after running those commands above, it's necessary to unplug DepthAI from USB and plug it back in.  So we should change the error message to say:

> To correct this, please:
> 1.  Run the following commands to set the udev rules for DepthAI:
> echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
> sudo udevadm control --reload-rules && udevadm trigger
> 2.  Unplug device USB.
> 3.  Plug device USB back in.

If you don't unplug/replug you see these errors:
image

And after unplugging and replugging it successfully runs:
image

**Comment by Luxonis-Brandon** [comment]
This LGTM thanks @szabi-luxonis !

**Pull request merged**
