### PR TITLE
Basic integration test: iterate through all stream combinations

### PR DESCRIPTION
**Pull request by GergelySzabolcs**
Usage:
python3 integration_test.py
The script will generate all combinations of streams defined in `streams`.
If USB_version is set to 2, it will limit the fps of the streams, else it won't.

### CODE REVIEW

**Comment by szabi-luxonis** [comment]
Integration test for DepthAI.
    Generates all combinations of streams defined in "streams", runs each of them for maximum of "timeout" seconds.
    The logs are written into integration_test.log.
    
    Example usage: python3 integration_test.py -usb=2 -to=10
    python3 integration_test.py -usb=3 -to=60

**Comment by Luxonis-Brandon** [comment]
TLDR: LGTM

So I'm not sure if this matters WRT this test, but I noticed when running a BW1093 (single-camera) with this integration_test.py, the watchdog has to go into recovery with some permutations.

So I think this actually means this integration_test is doing its job, discovering that this crash occurs.  So I'd say the integration_test.py is likely good to go.  And I'll upload the log and create a new issue for the crash that occurs when an invalid stream combination is pushed to the BW1093.

Thoughts?

**Comment by Luxonis-Brandon** [comment]
FWIW, it looks like integration_test.py did catch these errors and log them properly, which is great!
rares@beth:~/depthai-python-extras$ cat *.log
2020-04-08 18:07:00,995 INFO python3 depthai.py -co '{"streams": ["previewout"]}'
2020-04-08 18:07:30,997 INFO returned succesfully
2020-04-08 18:07:34,000 INFO python3 depthai.py -co '{"streams": ["left"]}'
2020-04-08 18:07:45,347 INFO returned with error code: 10
2020-04-08 18:07:48,351 INFO python3 depthai.py -co '{"streams": ["right"]}'
2020-04-08 18:07:59,678 INFO returned with error code: 10
2020-04-08 18:08:02,681 INFO python3 depthai.py -co '{"streams": ["depth_sipp"]}'
2020-04-08 18:08:14,028 INFO returned with error code: 10
2020-04-08 18:08:17,032 INFO python3 depthai.py -co '{"streams": ["previewout","metaout"]}'
2020-04-08 18:08:47,034 INFO returned succesfully
2020-04-08 18:08:50,037 INFO python3 depthai.py -co '{"streams": ["previewout","left"]}'
2020-04-08 18:09:20,039 INFO returned succesfully
2020-04-08 18:09:23,043 INFO python3 depthai.py -co '{"streams": ["previewout","right"]}'
2020-04-08 18:09:53,045 INFO returned succesfully
2020-04-08 18:09:56,048 INFO python3 depthai.py -co '{"streams": ["previewout","depth_sipp"]}'
2020-04-08 18:10:26,050 INFO returned succesfully
2020-04-08 18:10:29,054 INFO python3 depthai.py -co '{"streams": ["metaout","left"]}'
2020-04-08 18:10:59,056 INFO returned succesfully
2020-04-08 18:11:02,056 INFO python3 depthai.py -co '{"streams": ["metaout","right"]}'
2020-04-08 18:11:32,058 INFO returned succesfully
2020-04-08 18:11:35,059 INFO python3 depthai.py -co '{"streams": ["metaout","depth_sipp"]}'
2020-04-08 18:12:05,061 INFO returned succesfully
2020-04-08 18:12:08,065 INFO python3 depthai.py -co '{"streams": ["left","right"]}'
2020-04-08 18:12:19,398 INFO returned with error code: 10
2020-04-08 18:12:22,400 INFO python3 depthai.py -co '{"streams": ["left","depth_sipp"]}'
2020-04-08 18:12:33,733 INFO returned with error code: 10
2020-04-08 18:12:36,736 INFO python3 depthai.py -co '{"streams": ["right","depth_sipp"]}'
2020-04-08 18:12:48,070 INFO returned with error code: 10
2020-04-08 18:12:51,073 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","left"]}'
2020-04-08 18:13:21,075 INFO returned succesfully
2020-04-08 18:13:24,079 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","right"]}'
2020-04-08 18:13:54,081 INFO returned succesfully
2020-04-08 18:13:57,084 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","depth_sipp"]}'
2020-04-08 18:14:27,086 INFO returned succesfully
2020-04-08 18:14:30,090 INFO python3 depthai.py -co '{"streams": ["previewout","left","right"]}'
2020-04-08 18:15:00,092 INFO returned succesfully
2020-04-08 18:15:03,095 INFO python3 depthai.py -co '{"streams": ["previewout","left","depth_sipp"]}'
2020-04-08 18:15:33,097 INFO returned succesfully
2020-04-08 18:15:36,100 INFO python3 depthai.py -co '{"streams": ["previewout","right","depth_sipp"]}'
2020-04-08 18:16:06,102 INFO returned succesfully
2020-04-08 18:16:09,106 INFO python3 depthai.py -co '{"streams": ["metaout","left","right"]}'
2020-04-08 18:16:39,108 INFO returned succesfully
2020-04-08 18:16:42,111 INFO python3 depthai.py -co '{"streams": ["metaout","left","depth_sipp"]}'
2020-04-08 18:17:12,113 INFO returned succesfully
2020-04-08 18:17:15,116 INFO python3 depthai.py -co '{"streams": ["metaout","right","depth_sipp"]}'
2020-04-08 18:17:45,118 INFO returned succesfully
2020-04-08 18:17:48,122 INFO python3 depthai.py -co '{"streams": ["left","right","depth_sipp"]}'
2020-04-08 18:17:59,454 INFO returned with error code: 10
2020-04-08 18:18:02,458 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","left","right"]}'
2020-04-08 18:18:32,460 INFO returned succesfully
2020-04-08 18:18:35,460 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","left","depth_sipp"]}'
2020-04-08 18:19:05,462 INFO returned succesfully
2020-04-08 18:19:08,466 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","right","depth_sipp"]}'
2020-04-08 18:19:38,467 INFO returned succesfully
2020-04-08 18:19:41,468 INFO python3 depthai.py -co '{"streams": ["previewout","left","right","depth_sipp"]}'
2020-04-08 18:20:11,470 INFO returned succesfully
2020-04-08 18:20:14,472 INFO python3 depthai.py -co '{"streams": ["metaout","left","right","depth_sipp"]}'
2020-04-08 18:20:44,475 INFO returned succesfully
2020-04-08 18:20:47,478 INFO python3 depthai.py -co '{"streams": ["previewout","metaout","left","right","depth_sipp"]}'
2020-04-08 18:21:17,480 INFO returned succesfully

**Comment by szabi-luxonis** [comment]
Yes, if process watchdog gets triggered it's reported as error, if only USB watchdog is triggered is not considered error, since it can recover smoothly.
@Luxonis-Brandon

**Comment by Luxonis-Brandon** [comment]
LGTM.  Thanks!

**Pull request merged**
